// Tutorial
export const SAMPLE_INCREMENT = "SAMPLE_INCREMENT";
export const SAMPLE_DECREMENT = "SAMPLE_DECREMENT";
export const SAMPLE_INCREMENT_ASYNC = "SAMPLE_INCREMENT_ASYNC";

// Sample
export const SUBMIT_SAMPLE_REQUEST = "SUBMIT_SAMPLE_REQUEST";
