// Tutorial
export const SAMPLE_INCREMENT = "SAMPLE_INCREMENT";
export const SAMPLE_DECREMENT = "SAMPLE_DECREMENT";
export const SAMPLE_INCREMENT_ASYNC = "SAMPLE_INCREMENT_ASYNC";

// Sample
export const SUBMIT_SAMPLE_REQUEST = "SUBMIT_SAMPLE_REQUEST";
export const SUBMIT_SAMPLE_SUCCESS = "SUBMIT_SAMPLE_SUCCESS";
export const SUBMIT_SAMPLE_FAILURE = "SUBMIT_SAMPLE_FAILURE";

export const GET_SAMPLES_REQUEST = "GET_SUMPLES_REQUEST";
export const GET_SAMPLES_SUCCESS = "GET_SUMPLES_SUCCESS";
export const GET_SAMPLES_FAILURE = "GET_SUMPLES_FAILURE";
