CREATE DATABASE IF NOT EXISTS `go-random` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE DATABASE IF NOT EXISTS `go-random_test1` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE DATABASE IF NOT EXISTS `go-random_test2` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
CREATE DATABASE IF NOT EXISTS `go-random_test3` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

CREATE USER 'random'@'%' IDENTIFIED BY 'random';  
GRANT ALL PRIVILEGES ON *.* TO 'random'@'%' WITH GRANT OPTION;  
