// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package registry

import (
	"github.com/google/wire"
	"github.com/ktakenaka/go-random/backend/app/config"
	"github.com/ktakenaka/go-random/backend/app/domain/repository"
	"github.com/ktakenaka/go-random/backend/app/domain/service"
	"github.com/ktakenaka/go-random/backend/app/external/database"
	"github.com/ktakenaka/go-random/backend/app/interface/adaptor/restclient"
	"github.com/ktakenaka/go-random/backend/app/interface/persistence/mysql"
	"github.com/ktakenaka/go-random/backend/app/usecase"
	database2 "github.com/ktakenaka/go-random/backend/pkg/infra/database"
)

// Injectors from usecase.go:

func InitializeSampleUsecase() *usecase.SampleUsecase {
	db := database.MySQLConnection()
	sampleRepository := mysql.NewSampleRepository(db)
	sampleService := service.NewSampleService(sampleRepository)
	sampleUsecase := usecase.NewSampleUsecase(sampleRepository, sampleService)
	return sampleUsecase
}

func InitializeSignInUsecase() *usecase.SignInUsecase {
	oauth2Config := config.GetGoogleOauthConfig()
	googleRepository := restclient.NewGoogleRepository(oauth2Config)
	db := database.MySQLConnection()
	userRepository := mysql.NewUserRepository(db)
	signInUsecase := usecase.NewSignInUsecase(googleRepository, userRepository)
	return signInUsecase
}

// usecase.go:

var (
	SampleUsecaseSet = wire.NewSet(
		sampleRepositorySet, service.NewSampleService, usecase.NewSampleUsecase,
	)

	sampleRepositorySet = wire.NewSet(mysql.NewSampleRepository, database.MySQLConnection, wire.Bind(new(repository.SampleRepository), new(*mysql.SampleRepository)), wire.Bind(new(repository.DBConnection), new(*database2.DB)))

	SignInUsecaseSet = wire.NewSet(
		googleRepositorySet,
		userRepositorySet, usecase.NewSignInUsecase,
	)

	googleRepositorySet = wire.NewSet(config.GetGoogleOauthConfig, restclient.NewGoogleRepository, wire.Bind(new(repository.GoogleRepository), new(*restclient.GoogleRepository)))

	userRepositorySet = wire.NewSet(mysql.NewUserRepository, database.MySQLConnection, wire.Bind(new(repository.UserRepository), new(*mysql.UserRepository)))
)
