// Tutorial
export const SAMPLE_INCREMENT = "SAMPLE_INCREMENT";
export const SAMPLE_DECREMENT = "SAMPLE_DECREMENT";
export const SAMPLE_INCREMENT_ASYNC = "SAMPLE_INCREMENT_ASYNC";

// App
export const CHANGE_LOCATION = "CHANGE_LOCATION";
export const SET_MESSAGE = "SET_MESSAGE";
export const UNSET_MESSAAGE = "UNSET_MESSAGE";

// Sample
export const SUBMIT_SAMPLE_REQUEST = "SUBMIT_SAMPLE_REQUEST";
export const SUBMIT_SAMPLE_SUCCESS = "SUBMIT_SAMPLE_SUCCESS";
export const SUBMIT_SAMPLE_FAILURE = "SUBMIT_SAMPLE_FAILURE";

export const UPDATE_SAMPLE_REQUEST = "UPDATE_SAMPLE_REQUEST";
export const UPDATE_SAMPLE_SUCCESS = "UPDATE_SAMPLE_SUCCESS";
export const UPDATE_SAMPLE_FAILURE = "UPDATE_SAMPLE_FAILURE";

export const GET_SAMPLES_REQUEST = "GET_SAMPLES_REQUEST";
export const GET_SAMPLES_SUCCESS = "GET_SAMPLES_SUCCESS";
export const GET_SAMPLES_FAILURE = "GET_SAMPLES_FAILURE";

export const GET_SAMPLE_REQUEST = "GET_SAMPLE_REQUEST";
export const GET_SAMPLE_SUCCESS = "GET_SAMPLE_SUCCESS";
export const GET_SAMPLE_FAILURE = "GET_SAMPLE_FAILURE";

export const DELETE_SAMPLE_REQUEST = "DELETE_SAMPLE_REQUEST";
export const DELETE_SAMPLE_SUCCESS = "DELETE_SAMPLE_SUCCESS";
export const DELETE_SAMPLE_FAILURE = "DELETE_SAMPLE_FAILURE";

export const IMPORT_SAMPLES_REQUEST = "IMPORT_SAMPLES_REQUEST";
export const IMPORT_SAMPLES_SUCCESS = "IMPORT_SAMPLES_SUCCESS";
export const IMPORT_SAMPLES_FAILURE = "IMPORT_SAMPLES_FAILURE";

export const CLEANUP_SAMPLE = "CLEANUP_SAMPLE";

// Session
export const CREATE_SESSION_REQUEST = "CREATE_SESSION_REQUEST";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_FAILURE = "CREATE_SESSION_FAILS";
