// Code generated by goderive DO NOT EDIT.

package entity

// deriveEqual returns whether this and that are equal.
func deriveEqual(this, that *Sample) bool {
	return (this == nil && that == nil) ||
		this != nil && that != nil &&
			this.ID == that.ID &&
			this.CreatedAt.Equal(that.CreatedAt) &&
			this.UpdatedAt.Equal(that.UpdatedAt) &&
			this.Title == that.Title &&
			((this.Content == nil && that.Content == nil) || (this.Content != nil && that.Content != nil && *(this.Content) == *(that.Content))) &&
			this.UserID == that.UserID
}
