// Code generated by goderive DO NOT EDIT.

package entity

// deriveEqual returns whether this and that are equal.
func deriveEqual(this, that *Sample) bool {
	return (this == nil && that == nil) ||
		this != nil && that != nil &&
			deriveEqual_(&this.Model, &that.Model) &&
			this.Title == that.Title &&
			this.Content == that.Content &&
			this.UserID == that.UserID
}

// deriveEqual_ returns whether this and that are equal.
func deriveEqual_(this, that *Model) bool {
	return (this == nil && that == nil) ||
		this != nil && that != nil &&
			this.ID == that.ID &&
			this.CreatedAt.Equal(that.CreatedAt) &&
			this.UpdatedAt.Equal(that.UpdatedAt)
}
