// Code generated by goderive DO NOT EDIT.

package entity

// deriveEqual returns whether this and that are equal.
func deriveEqual(this, that *Sample) bool {
	return (this == nil && that == nil) ||
		this != nil && that != nil &&
			this.ID == that.ID &&
			this.CreatedAt == that.CreatedAt &&
			this.UpdatedAt == that.UpdatedAt &&
			this.Title == that.Title &&
			this.Content == that.Content &&
			this.UserID == that.UserID &&
			((this.Hoge == nil && that.Hoge == nil) || (this.Hoge != nil && that.Hoge != nil && *(this.Hoge) == *(that.Hoge)))
}
